#include "dab/dab_api_io.h"
#include "utils/hi_log.h"

using namespace std;

static const string PNG_BASE64 = "iVBORw0KGgoAAAANSUhEUgAAAaIAAAEDCAYAAAB3SwAkAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAPISURBVHhe7dUxAQAgDMAwwL/n8SOAPslZA90zMwsAIucNAPCTEQGQMiIAUkYEQMqIAEgZEQApIwIgZUQApIwIgJQRAZAyIgBSRgRAyogASBkRACkjAiBlRACkjAiAlBEBkDIiAFJGBEDKiABIGREAKSMCIGVEAKSMCICUEQGQMiIAUkYEQMqIAEgZEQApIwIgZUQApIwIgJQRAZAyIgBSRgRAyogASBkRACkjAiBlRACkjAiAlBEBkDIiAFJGBEDKiABIGREAKSMCIGVEAKSMCICUEQGQMiIAUkYEQMqIAEgZEQApIwIgZUQApIwIgJQRAZAyIgBSRgRAyogASBkRACkjAiBlRACkjAiAlBEBkDIiAFJGBEDKiABIGREAKSMCIGVEAKSMCICUEQGQMiIAUkYEQMqIAEgZEQApIwIgZUQApIwIgJQRAZAyIgBSRgRAyogASBkRACkjAiBlRACkjAiAlBEBkDIiAFJGBEDKiABIGREAKSMCIGVEAKSMCICUEQGQMiIAUkYEQMqIAEgZEQApIwIgZUQApIwIgJQRAZAyIgBSRgRAyogASBkRACkjAiBlRACkjAiAlBEBkDIiAFJGBEDKiABIGREAKSMCIGVEAKSMCICUEQGQMiIAUkYEQMqIAEgZEQApIwIgZUQApIwIgJQRAZAyIgBSRgRAyogASBkRACkjAiBlRACkjAiAlBEBkDIiAFJGBEDKiABIGREAKSMCIGVEAKSMCICUEQGQMiIAUkYEQMqIAEgZEQApIwIgZUQApIwIgJQRAZAyIgBSRgRAyogASBkRACkjAiBlRACkjAiAlBEBkDIiAFJGBEDKiABIGREAKSMCIGVEAKSMCICUEQGQMiIAUkYEQMqIAEgZEQApIwIgZUQApIwIgJQRAZAyIgBSRgRAyogASBkRACkjAiBlRACkjAiAlBEBkDIiAFJGBEDKiABIGREAKSMCIGVEAKSMCICUEQGQMiIAUkYEQMqIAEgZEQApIwIgZUQApIwIgJQRAZAyIgBSRgRAyogASBkRACkjAiBlRACkjAiAlBEBkDIiAFJGBEDKiABIGREAKSMCIGVEAKSMCICUEQGQMiIAUkYEQMqIAEgZEQApIwIgZUQApIwIgJQRAZAyIgBSRgRAyogASBkRACkjAiBlRACkjAiAlBEBkDIiAFJGBEDKiABIGREAKSMCIGVEAKSMCICUEQGQMiIAUkYEQMqIAEgZEQApIwIgZUQApIwIgJQRAZAyIgBSRgRAyogASBkRACkjAiBlRACkjAiAlBEBkLrs+gYCyNwulgAAAABJRU5ErkJggg==";


bool dab_api_getKeyList(vector<string>& list) {
	list.push_back("KEY_POWER");
    list.push_back("KEY_HOME");
    list.push_back("KEY_MENU");
    list.push_back("KEY_EXIT");
    list.push_back("KEY_INFO");
    list.push_back("KEY_UP");
    list.push_back("KEY_RIGHT");
    list.push_back("KEY_DOWN");
    list.push_back("KEY_LEFT");
    list.push_back("KEY_ENTER");
    list.push_back("KEY_BACK");
	return true;
}

bool dab_api_pressKey(const char* key, int durationMs) {
	DABLOG_INFO("key:%s,durationMs:%d", key, durationMs);
	return true;
}

bool dab_api_catpureImage2png(std::string& content) {
	content = PNG_BASE64;
	return true;
}
